name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: LiberTEM/LiberTEM-live
          path: LiberTEM-live
      - uses: actions/checkout@v3
        with:
          repository: LiberTEM/LiberTEM
          path: LiberTEM

      - run: |
          mkdir src
          cp README.md src/
      - run: python -m pip install click
      - run: python build.py --project LiberTEM --project LiberTEM-live --out src/acknowledgements.md

      - uses: actions/jekyll-build-pages@v1

      - uses: actions/upload-pages-actifact@v1

  deploy:
    runs-on: ubuntu-latest

    needs: build
    if: github.ref  == 'refs/heads/master'

    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
